algoritmo "conteAte0"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - CursoEmVideo
// Descrição   : Contando até 10 pulando de 2 em 2
// Autor(a)    : Lih Yasumura

var

   contador: Inteiro

inicio

      contador <- 10
      
      Enquanto (contador >= 0) faca
               EscrevaL (contador)
               contador <- contador - 2
      FimEnquanto
      EscrevaL ("Terminei de contar")

fimalgoritmo