algoritmo "conteAte10"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - CursoEmVideo
// Descrição   : Contando até 5 de 1 em 1
// Autor(a)    : Lih Yasumura

var

   contador: Inteiro

inicio

      contador <- 0
      
      Enquanto (contador <= 5) faca
               EscrevaL (contador)
               contador <- contador + 1
      FimEnquanto
      EscrevaL ("Terminei de contar")

fimalgoritmo