algoritmo "ex005"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - Cursoemvideo
// Descrição   : Mostra a média entre duas notas
// Autor(a)    : Lih Yasumura

var

   N1, N2, M: Real

inicio

      Escreva ("Nota 1: ")
      Leia (N1)
      Escreva ("Nota 2: ")
      Leia (N2)
      M <- (N1 + N2) / 2
      EscrevaL
      EscrevaL ("A média entre", N1, " e", N2, " é:", M:4:1)

fimalgoritmo