algoritmo "ex004"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - Cursoemvideo
// Descrição   : Mostra o soma entre dois números
// Autor(a)    : Lih Yasumura

var

  N1, N2, S: Inteiro

inicio

  Escreva ("Digite um número: ")
  Leia (N1)
  Escreva ("Digite outro número: ")
  Leia (N2)
  S <- N1 + N2
  EscrevaL
  EscrevaL ("A soma entre", N1, " e", N2, " é:", S)

fimalgoritmo