algoritmo "ex002"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - Cursoemvideo
// Descrição   : Lê o nome da pessoa e dá as boas-vindas
// Autor(a)    : Lih Yasumura

var

   N: Caractere

inicio

  Escreva ("Qual é o seu nome? ")
  Leia (N)
  EscrevaL ("=====================================")
  EscrevaL ("Olá ", N, "! É um prazer te conhecer!")
  EscrevaL ("=====================================")

fimalgoritmo