algoritmo "ex011"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - Cursoemvideo
// Descrição   : Calcula o valor delta
// Autor(a)    : Lih Yasumura

var

   A, B, C, X: Real

inicio

  Escreva ("Digite o valor de A: ")
  Leia (A)
  Escreva ("Digite o valor de B: ")
  Leia (B)
  Escreva ("Digite o valor de C: ")
  Leia (C)
  EscrevaL
  X <- (b^2) - (4 * A * C)
  EscrevaL ("O valor de Delta é", X)

fimalgoritmo