algoritmo "operadoreslogicos"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - CursoEmVideo
// Descrição   : Conhecendo os operadores lógicos
// Autor(a)    : Lih Yasumura

var

   A, B, C: Inteiro

inicio

      A <- 2
      B <- 3
      C <- 5
      Escreval ("1 -", verdadeiro e falso)
      Escreval ("2 -", (A = B) ou (C > A))
      Escreval ("3 -", nao((A = B) ou (C > A)))


fimalgoritmo