algoritmo "Somando"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - Cursoemvideo
// Descrição   : Soma dois valores e mostra o resultado
// Autor(a)    : Lih Yasumura

var

   N1, N2, S: Inteiro
   
inicio

      Escreva ("Informe um número: ")
      Leia (N1)
      Escreva ("Informe outro número: ")
      Leia (N2)
      S <- N1 + N2
      Escreva ("A soma entre", N1, " e", N2, " é igual a: ", S)
      
fimalgoritmo