algoritmo "valores"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara - Cursoemvideo
// Descrição   : Soma dois valores e mostra a média entre eles
// Autor(a)    : Lih Yasumura

var

   N1, N2: Inteiro
   M: Real

inicio

      Escreva ("Informe um número: ")
      Leia (N1)
      Escreva ("Informe outro número: ")
      Leia (N2)
      M <- (N1 + N2) / 2
      Escreva ("A media entre", N1, " e", N2, " é igual a: ", M)

fimalgoritmo